# This workflow will build a Java project with Ant
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Triggers Java CI
run-name: Usando mis primeros triggers
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
     alerta:
       description: 'nivel'
       required: true
       default: medio
       type: choice
       options:
       - bajo
       - medio
     tags:
         description: 'Opcional'
         required: false
         type: boolean
     environment:
       description: 'Objetivo'
       type: string
       required: true
jobs:
  build:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
    - name: checkout
    - uses: actions/checkout@v4
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        
    - name: Verify Java installation
      run: |
        java -version
        javac -version
        echo "Java setup complete on Linux"
        
    - name: Compile Java program
      run: javac HelloWorld.java
      
    - name: Run Java program
      run: java -cp . HelloWorld
      
    - name: List generated files
      run: ls -la *.class
